stages:
  split:
    cmd: python src/data/split_data.py
    deps:
      - data/raw/raw.csv
      - src/data/split_data.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python src/data/normalize_data.py
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - src/data/normalize_data.py
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv
      - models/scaler.pkl

  grid_search:
    cmd: python src/data/grid_search.py
    deps:
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - src/data/grid_search.py
    outs:
      - models/best_params.pkl

  train:
    cmd: python src/data/train_model.py
    deps:
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - models/best_params.pkl
      - src/data/train_model.py
    outs:
      - models/trained_model.pkl

  evaluate:
    cmd: python src/data/evaluate_model.py
    deps:
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
      - models/trained_model.pkl
      - src/data/evaluate_model.py
    outs:
      - metrics/scores.json
      - data/predictions.csv